## Numpy

Импортировать NumPy под именем np

In [1]:
import numpy as np

Создать вектор (одномерный массив) размера 10, заполненный нулями

In [2]:
zero_array = np.zeros(10)
zero_array

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

Создать вектор размера 10, заполненный единицами

In [3]:
one_array = np.ones(10)
one_array

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

Создать вектор размера 10, заполненный числом 2.5

In [9]:
array = np.ndarray(10)
array.fill(2.5)
array

array([ 2.5,  2.5,  2.5,  2.5,  2.5,  2.5,  2.5,  2.5,  2.5,  2.5])

Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [11]:
zero_array = np.zeros(10)
zero_array[4]=1
zero_array

array([ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.])

Развернуть вектор (первый становится последним)

In [16]:
array = np.arange(10)
print(array)
array = np.flipud(array)
print(array)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [28]:
a = np.arange(9)
print(a)
a= np.reshape(a, [3,3])
print(a)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [37]:
a = [1,2,0,0,4,0]
notZeroIndex = np.nonzero(a)
notZeroIndex

(array([0, 1, 4]),)

Создать 3x3 единичную матрицу

In [38]:
a = np.ones([3,3])
a

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

Создать массив 3x3x3 со случайными значениями

In [42]:
a = np.random.rand(3,3,3)
a

array([[[ 0.43567068,  0.94870016,  0.62654721],
        [ 0.64131625,  0.74937059,  0.02767968],
        [ 0.98413708,  0.29444045,  0.37023302]],

       [[ 0.98094334,  0.6518936 ,  0.50371369],
        [ 0.08947218,  0.44890919,  0.35399788],
        [ 0.53274564,  0.68557484,  0.54838265]],

       [[ 0.71237021,  0.45013383,  0.05332443],
        [ 0.21144816,  0.41236207,  0.10915008],
        [ 0.46268324,  0.79445781,  0.54946498]]])

Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [46]:
a = np.random.rand(30)
a.mean()

0.43493172239968081

Перемножить матрицы 5x3 и 3x2

In [48]:
a = np.random.rand(5,3)
b = np.random.rand(3,2)
resultMtx = a@b
print(resultMtx)

[[ 0.49600906  0.58087295]
 [ 0.81640786  0.65658201]
 [ 0.6583533   0.76407712]
 [ 0.4494371   0.20449894]
 [ 1.0166717   0.35496276]]


Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [61]:
a = np.random.uniform(0.000001, 1, 10)

Заменить максимальный элемент на ноль

In [69]:
a = [1,2,3,5,123,9]
a[np.argmax(a)] = 0
print(a)

[1, 2, 3, 5, 0, 9]


Преобразовать массив из float в int

In [72]:
a = np.random.uniform(0, 100, 10)
print(a)
a = a.astype('int64')
print(a)



[ 42.40888337  17.80317632  22.9839401    2.44046235  53.24201141
   6.16850729  55.00412742   2.86535286  73.1213638   23.20656648]
[42 17 22  2 53  6 55  2 73 23]


Дан массив (10,2) координат, найти расстояние от каждой точки до каждой

In [89]:
from scipy.spatial import distance
a = np.random.randint(0,100,size = [10,2])
distances = distance.cdist(a, a, 'euclidean')

Случайно расположить p элементов в 2D массив

In [105]:
p = np.arange(1,10)
a = np.zeros([5,4])
for ix, iy in np.ndindex(a.shape):
    a[ix,iy] = np.random.choice(p, replace=True)

Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [133]:
a = np.arange(1,6)
b = np.zeros([5,4])
b[:,0]=a
b = b.reshape(1,20)
b = b[0,0:-3]

Найти наиболее частое значение в массиве

In [141]:
from scipy import stats
a = [1,2,3,4,1,2,2,5]
mode = stats.mode(a)[0][0]

Найти n наибольших значений в массиве

In [147]:
x = np.array([1,2,3,4,1,99,4,5])
n = 3
print(x[np.argsort(x)[-n:]])
print(np.argsort(x)[-n:])

[ 4  5 99]
[6 7 5]


## Pandas - изучение данных

Перейти по ссылке [Kaggle]( https://www.kaggle.com/openfoodfacts/world-food-facts)

Скачать датасет на свой компьютер и распаковать

Считать csv файл в датафрейм food

In [177]:
import pandas as pd
food = pd.read_csv("en.openfoodfacts.org.products.tsv", sep="\t", low_memory=False)

Посмотреть первые 5 записей

In [178]:
food.head(5)

code                                                url  \
0  0000000003087  http://world-en.openfoodfacts.org/product/0000...   
1  0000000004530  http://world-en.openfoodfacts.org/product/0000...   
2  0000000004559  http://world-en.openfoodfacts.org/product/0000...   
3  0000000016087  http://world-en.openfoodfacts.org/product/0000...   
4  0000000016094  http://world-en.openfoodfacts.org/product/0000...   

                      creator   created_t      created_datetime  \
0  openfoodfacts-contributors  1474103866  2016-09-17T09:17:46Z   
1             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
2             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
3             usda-ndb-import  1489055731  2017-03-09T10:35:31Z   
4             usda-ndb-import  1489055653  2017-03-09T10:34:13Z   

  last_modified_t last_modified_datetime                    product_name  \
0      1474103893   2016-09-17T09:18:13Z              Farine de blé noir   
1      1489069957   2017-03-09T14:32:37Z  Banana Chips Sweetened (Whole)   
2      1489069957   2017-03-09T14:32:37Z                         Peanuts   
3      1489055731   2017-03-09T10:35:31Z          Organic Salted Nut Mix   
4      1489055653   2017-03-09T10:34:13Z                 Organic Polenta   

  generic_name quantity         ...         fruits-vegetables-nuts_100g  \
0          NaN      1kg         ...                                 NaN   
1          NaN      NaN         ...                                 NaN   
2          NaN      NaN         ...                                 NaN   
3          NaN      NaN         ...                                 NaN   
4          NaN      NaN         ...                                 NaN   

  fruits-vegetables-nuts-estimate_100g collagen-meat-protein-ratio_100g  \
0                                  NaN                              NaN   
1                                  NaN                              NaN   
2                                  NaN                              NaN   
3                                  NaN                              NaN   
4                                  NaN                              NaN   

  cocoa_100g chlorophyl_100g carbon-footprint_100g nutrition-score-fr_100g  \
0        NaN             NaN                   NaN                     NaN   
1        NaN             NaN                   NaN                    14.0   
2        NaN             NaN                   NaN                     0.0   
3        NaN             NaN                   NaN                    12.0   
4        NaN             NaN                   NaN                     NaN   

  nutrition-score-uk_100g glycemic-index_100g water-hardness_100g  
0                     NaN                 NaN                 NaN  
1                    14.0                 NaN                 NaN  
2                     0.0                 NaN                 NaN  
3                    12.0                 NaN                 NaN  
4                     NaN                 NaN                 NaN  

[5 rows x 163 columns]

Сколько наблюдений в наборе данных?


In [179]:
food.shape[0]

356027

Сколько столбцов в наборе данных?

In [180]:
food.shape[1]

163

Напечатайте все названия столбцов

In [181]:
print(food.columns)

Index(['code', 'url', 'creator', 'created_t', 'created_datetime',
       'last_modified_t', 'last_modified_datetime', 'product_name',
       'generic_name', 'quantity',
       ...
       'fruits-vegetables-nuts_100g', 'fruits-vegetables-nuts-estimate_100g',
       'collagen-meat-protein-ratio_100g', 'cocoa_100g', 'chlorophyl_100g',
       'carbon-footprint_100g', 'nutrition-score-fr_100g',
       'nutrition-score-uk_100g', 'glycemic-index_100g',
       'water-hardness_100g'],
      dtype='object', length=163)


Какое название у 105 столбца?

In [182]:
food.columns[104]

'-glucose_100g'

Какой тип наблюдений в 105 столбце?

In [184]:
food.dtypes[104]

dtype('float64')

Как проиндексирован набор данных?

In [ ]:
# Не понял вопроса?

Каково значение имени продукта в 19-м наблюдении?

In [185]:
food.loc[19]['product_name']

'Organic Oat Groats'

## Pandas - фильтрация данных

Считать данные по  [адресу](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv). 
Присвоить переменной chipo

In [205]:
chipo = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv", sep="\t")

In [206]:
chipo.head()

order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   

                                  choice_description item_price  
0                                                NaN     $2.39   
1                                       [Clementine]     $3.39   
2                                            [Apple]     $3.39   
3                                                NaN     $2.39   
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98

Как много продуктов стоят более чем $10.00?

In [216]:
chipo['item_price'] = chipo['item_price'].replace('\$','', regex=True)
chipo['item_price'] = chipo['item_price'].astype('float')
chipo[chipo['item_price'] > 10].shape[0]

1130

Какова цена каждого предмета? Напечатать столбцы item_name и item_price

In [228]:
chipo.loc[:,['item_name','item_price']]

item_name  item_price
0              Chips and Fresh Tomato Salsa        2.39
1                                      Izze        3.39
2                          Nantucket Nectar        3.39
3     Chips and Tomatillo-Green Chili Salsa        2.39
4                              Chicken Bowl       16.98
5                              Chicken Bowl       10.98
6                             Side of Chips        1.69
7                             Steak Burrito       11.75
8                          Steak Soft Tacos        9.25
9                             Steak Burrito        9.25
10                      Chips and Guacamole        4.45
11                     Chicken Crispy Tacos        8.75
12                       Chicken Soft Tacos        8.75
13                             Chicken Bowl       11.25
14                      Chips and Guacamole        4.45
15    Chips and Tomatillo-Green Chili Salsa        2.39
16                          Chicken Burrito        8.49
17                          Chicken Burrito        8.49
18                              Canned Soda        2.18
19                             Chicken Bowl        8.75
20                      Chips and Guacamole        4.45
21                         Barbacoa Burrito        8.99
22                         Nantucket Nectar        3.39
23                          Chicken Burrito       10.98
24                                     Izze        3.39
25             Chips and Fresh Tomato Salsa        2.39
26                             Chicken Bowl        8.49
27                         Carnitas Burrito        8.99
28                              Canned Soda        1.09
29                          Chicken Burrito        8.49
...                                     ...         ...
4592                       Barbacoa Burrito       11.75
4593                          Carnitas Bowl       11.75
4594                          Barbacoa Bowl       11.75
4595                           Chicken Bowl        8.75
4596                    Chips and Guacamole        4.45
4597                      Canned Soft Drink        1.25
4598                          Bottled Water        1.50
4599                           Chicken Bowl        8.75
4600                    Chips and Guacamole        4.45
4601                      Canned Soft Drink        1.25
4602                       Barbacoa Burrito        9.25
4603                       Barbacoa Burrito        9.25
4604                           Chicken Bowl        8.75
4605                    Chips and Guacamole        4.45
4606                      Canned Soft Drink        1.25
4607                          Steak Burrito       11.75
4608                         Veggie Burrito       11.25
4609                      Canned Soft Drink        1.25
4610                          Steak Burrito       11.75
4611                         Veggie Burrito       11.25
4612                          Carnitas Bowl        9.25
4613                                  Chips        2.15
4614                          Bottled Water        1.50
4615                     Chicken Soft Tacos        8.75
4616                    Chips and Guacamole        4.45
4617                          Steak Burrito       11.75
4618                          Steak Burrito       11.75
4619                     Chicken Salad Bowl       11.25
4620                     Chicken Salad Bowl        8.75
4621                     Chicken Salad Bowl        8.75

[4622 rows x 2 columns]

Отсортировать по имени предмета

In [247]:
chipo = chipo.sort_values(by='item_name', ascending=True)
chipo

order_id  quantity          item_name  \
3614      1448         1  6 Pack Soft Drink   
341        148         1  6 Pack Soft Drink   
3886      1558         1  6 Pack Soft Drink   
743        306         1  6 Pack Soft Drink   
3141      1253         1  6 Pack Soft Drink   
357        154         1  6 Pack Soft Drink   
388        168         1  6 Pack Soft Drink   
3875      1554         1  6 Pack Soft Drink   
4169      1664         1  6 Pack Soft Drink   
1124       465         1  6 Pack Soft Drink   
3010      1196         1  6 Pack Soft Drink   
4174      1666         1  6 Pack Soft Drink   
2108       849         1  6 Pack Soft Drink   
4535      1803         1  6 Pack Soft Drink   
2374       945         1  6 Pack Soft Drink   
3389      1360         2  6 Pack Soft Drink   
1755       708         1  6 Pack Soft Drink   
3693      1480         1  6 Pack Soft Drink   
3766      1508         1  6 Pack Soft Drink   
1392       566         1  6 Pack Soft Drink   
1758       709         1  6 Pack Soft Drink   
1976       798         1  6 Pack Soft Drink   
417        182         1  6 Pack Soft Drink   
879        363         1  6 Pack Soft Drink   
3789      1517         1  6 Pack Soft Drink   
1167       481         1  6 Pack Soft Drink   
3836      1537         1  6 Pack Soft Drink   
721        298         1  6 Pack Soft Drink   
298        129         1  6 Pack Soft Drink   
1279       520         1  6 Pack Soft Drink   
...        ...       ...                ...   
3163      1263         1       Veggie Salad   
4084      1635         1       Veggie Salad   
3471      1395         1       Veggie Salad   
2756      1094         1       Veggie Salad   
2996      1192         1       Veggie Salad   
295        128         1  Veggie Salad Bowl   
1316       536         1  Veggie Salad Bowl   
496        207         1  Veggie Salad Bowl   
1884       760         1  Veggie Salad Bowl   
2223       896         1  Veggie Salad Bowl   
4201      1677         1  Veggie Salad Bowl   
3223      1289         1  Veggie Salad Bowl   
4541      1805         1  Veggie Salad Bowl   
4109      1646         1  Veggie Salad Bowl   
455        195         1  Veggie Salad Bowl   
4261      1700         1  Veggie Salad Bowl   
2269       913         1  Veggie Salad Bowl   
186         83         1  Veggie Salad Bowl   
3293      1321         1  Veggie Salad Bowl   
960        394         1  Veggie Salad Bowl   
2683      1066         1  Veggie Salad Bowl   
4573      1818         1  Veggie Salad Bowl   
2156       869         1  Veggie Salad Bowl   
738        304         1  Veggie Soft Tacos   
2851      1132         1  Veggie Soft Tacos   
1395       567         1  Veggie Soft Tacos   
3889      1559         2  Veggie Soft Tacos   
781        322         1  Veggie Soft Tacos   
2384       948         1  Veggie Soft Tacos   
1699       688         1  Veggie Soft Tacos   

                                     choice_description  item_price  
3614                                           [Nestea]        6.49  
341                                         [Diet Coke]        6.49  
3886                                        [Diet Coke]        6.49  
743                                              [Coke]        6.49  
3141                                         [Lemonade]        6.49  
357                                              [Coke]        6.49  
388                                         [Diet Coke]        6.49  
3875                                        [Diet Coke]        6.49  
4169                                        [Diet Coke]        6.49  
1124                                             [Coke]        6.49  
3010                                        [Diet Coke]        6.49  
4174                                             [Coke]        6.49  
2108                                             [Coke]        6.49  
4535                                         [Lemonade]        6.49  
2374                                     

Сколько было заказано самого дорогого предмета?

In [254]:
#
max_price = chipo['item_price'][np.argmax(chipo['item_price'])]
chipo[chipo['item_price'] == max_price]['item_price'].count()

1

Сколько раз был заказан предмет "Veggie Salad Bowl"?

In [253]:
chipo[chipo['item_name']=='Veggie Salad Bowl']['item_name'].count()

18

Сколько раз люди заказали более чем 1 предмет "Canned Soda"?

In [285]:
sum(chipo[chipo['item_name']=='Canned Soda'].groupby(['order_id', 'item_name'])['order_id'].count() > 1)

9